function char_to_color(key)
%%%input may be diff..idk
%%%GOAL: EACH ASCII CHARACTER MAPS TO 2 OR 3 DIFF NUMS, EACH REPRESENTING A
%%% AN RGB VALUE. STORE THE POTENTIAL VALUES OF EACH CHARACTER

%%% I.E. IF IMAGE CONTAINS 100, 200, OR 300, ALL KNOWN TO FIT 'D'


%%%%STUFF TO NOT DO NOW:
%THIS FUNCTION
%RGB STUFF; ASSUME 1 CHANNEL FOR NOW